version: "3.9"

services:

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=task_management_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'

#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"  # RabbitMQ server port
#      - "15672:15672"  # RabbitMQ Management plugin port
#    environment:
#      RABBITMQ_DEFAULT_USER: user
#      RABBITMQ_DEFAULT_PASS: password
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq


volumes:
  postgres_data:
#  rabbitmq_data: