version: "3.9"

services:
  app:
      image: app
      build: .  # Путь к директории с Dockerfile
      container_name: fastapi_app  # Убедитесь, что имя контейнера не содержит дефисов перед подчеркиванием
      command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      environment:
        DATABASE: task_management_db
        SQL_HOST: db
        SQL_PORT: 5432
        SQL_USER: postgres
        SQL_PASSWORD: postgres
        SQL_DB: task_management_db
      depends_on:
          - db
      env_file:
        - app/.env

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=task_management_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'

volumes:
  postgres_data:
