"""Priority

Revision ID: a88654ca69a2
Revises: e2565a6719c2
Create Date: 2024-11-17 12:13:13.619208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88654ca69a2'
down_revision: Union[str, None] = 'e2565a6719c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('priority', sa.Enum('LOW', 'MIDDLE', 'HIGH', name='taskpriority', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'priority')
    # ### end Alembic commands ###
