"""Tasks status

Revision ID: f6059148a27f
Revises: 758aef918409
Create Date: 2024-11-14 00:19:34.364348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f6059148a27f'
down_revision: Union[str, None] = '758aef918409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tasks', 'status',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tasks', 'status',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###
