from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f7c81562e3bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('Tasks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('task_name', sa.String(), nullable=True),
                    sa.Column('task_descriptions', sa.String(), nullable=True),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('creator_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['creator_id'], ['Users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('Ssubscriptions',
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('task_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['task_id'], ['Tasks.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'task_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ssubscriptions')
    op.drop_table('Tasks')
    op.drop_table('Users')
    # ### end Alembic commands ###
